# H2 Database
spring.datasource.url=jdbc:h2:file:./BD_H2
spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ???? ????????? ????? MySQL ??? ?????????????
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ?????????? SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ?????????????? ???????? ?????

# deletes tables when the application is terminated
#spring.jpa.hibernate.ddl-auto=create-drop

# does not delete tables when the application is terminated
spring.jpa.hibernate.ddl-auto=update

# ??? ??? production (????? ??? ? update, ?? ???? ???? ???????? ? ??????? ?? ? ????????? Java ??????????? ??????????):
# spring.jpa.hibernate.ddl-auto=validate

# We allow the maintenance of static files
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**